# Generated by Django 5.2.8 on 2025-11-24 22:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_emergencia', models.CharField(max_length=100, verbose_name='Contacto de Emergencia')),
                ('telefono_emergencia', models.CharField(max_length=15, verbose_name='Teléfono de Emergencia')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe estar en formato: 12345678-9', regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('medico', 'Médico'), ('enfermera', 'Enfermera'), ('recepcionista', 'Recepcionista')], default='recepcionista', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Enfermera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(max_length=50, unique=True, verbose_name='Número de Registro Profesional')),
                ('turno', models.CharField(choices=[('manana', 'Mañana (08:00-16:00)'), ('tarde', 'Tarde (16:00-00:00)'), ('noche', 'Noche (00:00-08:00)')], default='manana', max_length=10)),
                ('area_asignada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área Asignada')),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enfermera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enfermera',
                'verbose_name_plural': 'Enfermeras',
                'ordering': ['usuario__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('numero_registro', models.CharField(max_length=50, unique=True, verbose_name='Número de Registro Profesional')),
                ('anos_experiencia', models.IntegerField(default=0, verbose_name='Años de Experiencia')),
                ('horario_atencion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Horario de Atención')),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['usuario__nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=5, null=True, verbose_name='Grupo Sanguíneo')),
                ('alergias', models.TextField(blank=True, null=True)),
                ('enfermedades_cronicas', models.TextField(blank=True, null=True, verbose_name='Enfermedades Crónicas')),
                ('medicamentos_actuales', models.TextField(blank=True, null=True, verbose_name='Medicamentos Actuales')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='gestor_app.paciente')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('motivo', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='gestor_app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='gestor_app.paciente')),
            ],
            options={
                'verbose_name': 'Cita Médica',
                'verbose_name_plural': 'Citas Médicas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_trabajo', models.CharField(default='Recepción General', max_length=100, verbose_name='Área de Trabajo')),
                ('horario', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recepcionista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepcionista',
                'verbose_name_plural': 'Recepcionistas',
                'ordering': ['usuario__nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamentos', models.TextField(verbose_name='Medicamentos (detalle, dosis y frecuencia)')),
                ('indicaciones', models.TextField()),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('vigencia', models.DateField(verbose_name='Vigencia hasta')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='gestor_app.cita')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_emitidas', to='gestor_app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='gestor_app.paciente')),
            ],
            options={
                'verbose_name': 'Receta Médica',
                'verbose_name_plural': 'Recetas Médicas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('presion_arterial', models.CharField(max_length=10, verbose_name='Presión Arterial (ej: 120/80)')),
                ('frecuencia_cardiaca', models.IntegerField(verbose_name='Frecuencia Cardíaca (lpm)')),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperatura (°C)')),
                ('frecuencia_respiratoria', models.IntegerField(verbose_name='Frecuencia Respiratoria (rpm)')),
                ('saturacion_oxigeno', models.IntegerField(verbose_name='Saturación de Oxígeno (%)')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='gestor_app.cita')),
                ('enfermera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signos_registrados', to='gestor_app.enfermera')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='gestor_app.paciente')),
            ],
            options={
                'verbose_name': 'Registro de Signos Vitales',
                'verbose_name_plural': 'Registros de Signos Vitales',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
