# Generated by Django 5.2.5 on 2025-12-02 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermera',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='recepcionista',
            name='activo',
        ),
    ]
