# Generated by Django 5.2.5 on 2025-12-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_app', '0002_remove_enfermera_activo_remove_medico_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='horario_atencion',
        ),
        migrations.AddField(
            model_name='medico',
            name='atiende_manana',
            field=models.BooleanField(default=True, verbose_name='Atiende en la mañana'),
        ),
        migrations.AddField(
            model_name='medico',
            name='atiende_tarde',
            field=models.BooleanField(default=True, verbose_name='Atiende en la tarde'),
        ),
        migrations.AddField(
            model_name='medico',
            name='dias_atencion',
            field=models.CharField(default='1,2,3,4,5', help_text='Días separados por comas (1=Lunes, 2=Martes, etc.)', max_length=20, verbose_name='Días de Atención'),
        ),
        migrations.AddField(
            model_name='medico',
            name='duracion_consulta',
            field=models.IntegerField(default=30, verbose_name='Duración de Consulta (minutos)'),
        ),
        migrations.AddField(
            model_name='medico',
            name='hora_fin_manana',
            field=models.TimeField(default='12:30', verbose_name='Hora Fin Mañana'),
        ),
        migrations.AddField(
            model_name='medico',
            name='hora_fin_tarde',
            field=models.TimeField(default='17:00', verbose_name='Hora Fin Tarde'),
        ),
        migrations.AddField(
            model_name='medico',
            name='hora_inicio_manana',
            field=models.TimeField(default='08:30', verbose_name='Hora Inicio Mañana'),
        ),
        migrations.AddField(
            model_name='medico',
            name='hora_inicio_tarde',
            field=models.TimeField(default='13:30', verbose_name='Hora Inicio Tarde'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'confirmada', 'en_curso'])), fields=('medico', 'fecha_hora'), name='unique_medico_fecha_hora_activa'),
        ),
    ]
