# Generated by Django 5.2.5 on 2025-12-10 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_app', '0003_remove_medico_horario_atencion_medico_atiende_manana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Medicamento')),
                ('gramos', models.DecimalField(decimal_places=2, help_text='Concentración del medicamento', max_digits=10, verbose_name='Gramos/Miligramos')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecetaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recetada', models.IntegerField(default=1, verbose_name='Cantidad Recetada')),
                ('dosis', models.CharField(help_text='Ej: 1 comprimido cada 8 horas', max_length=200, verbose_name='Dosis')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='gestor_app.medicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_recetados', to='gestor_app.recetamedica')),
            ],
            options={
                'verbose_name': 'Medicamento en Receta',
                'verbose_name_plural': 'Medicamentos en Recetas',
            },
        ),
    ]
