# Generated by Django 5.2.8 on 2025-12-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_app', '0004_medicamento_recetamedicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetamedica',
            name='medicamentos',
            field=models.TextField(blank=True, null=True, verbose_name='Medicamentos (detalle, dosis y frecuencia)'),
        ),
    ]
