# Generated by Django 5.2.8 on 2025-12-10 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_app', '0005_alter_recetamedica_medicamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetamedica',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='gestor_app.cita'),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='fecha_emision',
            field=models.DateTimeField(verbose_name='Fecha de Emisión'),
        ),
    ]
