# Generated by Django 5.2.8 on 2025-12-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_app', '0006_alter_recetamedica_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetamedica',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='indicaciones',
            field=models.TextField(verbose_name='Indicaciones Preventivas'),
        ),
    ]
