# Generated by Django 5.2.8 on 2025-12-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_app', '0007_alter_recetamedica_fecha_emision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetamedica',
            name='medicamentos',
        ),
    ]
